"""Seed a starter set of universities for international applicants.

The data here is sourced from each university's public admissions page and
widely-published rankings (QS / Times Higher Education / U.S. News). Acceptance
rates and tuition figures are rounded into discrete bands (selectivity_score,
aid_strength) on a 1-10 scale so we can sort and filter without claiming false
precision.

Notes on the scale we use here:

* selectivity_score (1-10): rough overall admit-rate band.
  10 = <5%, 9 = 5-10%, 8 = 10-15%, 7 = 15-25%, 6 = 25-40%, 5 = 40-60%,
  4 = 60-80%, 3 = >80%.
* aid_strength (1-10): how generous *international* financial aid is.
  10 = need-blind for internationals + meets 100% need
  8 = need-aware but meets 100% demonstrated need for admitted internationals
  6 = significant merit and/or need aid available
  4 = limited aid
  2 = effectively pay-your-way

Run:

    python -m src.seeds.seed_universities

The loader is idempotent: re-running updates existing rows by slug instead of
inserting duplicates.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional

from sqlalchemy.orm import Session

from ..database import SessionLocal
from ..models.university import University, WeightPreset


@dataclass
class UniversitySeed:
    slug: str
    name: str
    country: str
    region: Optional[str] = None
    city: Optional[str] = None
    application_system: Optional[str] = None
    application_source_url: Optional[str] = None
    short_description: Optional[str] = None
    weight_preset: WeightPreset = WeightPreset.balanced_holistic
    is_common_app: bool = False
    teaching_languages: list[str] = field(default_factory=list)
    major_strengths: list[str] = field(default_factory=list)
    education_years_required: Optional[int] = 12
    school_years_note: Optional[str] = None
    aid_type: Optional[str] = None
    aid_strength: Optional[int] = None
    selectivity_score: Optional[int] = None
    full_ride_possible: bool = False
    full_tuition_possible: bool = False
    aid_notes: Optional[str] = None
    funding_source_url: Optional[str] = None
    funding_source_title: Optional[str] = None
    eligibility_notes: Optional[str] = None


# Common-App needs the international-student-friendly switch.
COMMON_APP = "Common App"
COALITION = "Coalition"
UCAS = "UCAS"
DIRECT = "Direct"
UNI_ASSIST = "uni-assist (Germany)"
STUDIE_LINK = "Studielink (Netherlands)"
SISTEMA_UNIVERSITARIO = "Direct (Italy CISIA)"
SWE_INDEX = "universityadmissions.se"
JEX = "Direct (Japan EJU/JEX)"


# ---------------------------------------------------------------------------
# United States  (60 schools)
# ---------------------------------------------------------------------------
US: list[UniversitySeed] = [
    # Ivy League
    UniversitySeed("harvard-university", "Harvard University", "United States", "Northeast", "Cambridge, MA",
        application_system=COMMON_APP, application_source_url="https://college.harvard.edu/admissions",
        short_description="Private Ivy League research university; need-blind for international applicants.",
        weight_preset=WeightPreset.balanced_holistic, is_common_app=True,
        teaching_languages=["English"], major_strengths=["Liberal Arts", "Government", "Economics", "Computer Science", "Medicine"],
        aid_type="Need-based (need-blind for internationals)", aid_strength=10, selectivity_score=10,
        full_ride_possible=True, full_tuition_possible=True,
        aid_notes="Need-blind admissions for all applicants; commits to meeting 100% of demonstrated financial need with grants.",
        funding_source_url="https://college.harvard.edu/financial-aid",
        funding_source_title="Harvard Financial Aid"),
    UniversitySeed("yale-university", "Yale University", "United States", "Northeast", "New Haven, CT",
        application_system=COMMON_APP, application_source_url="https://admissions.yale.edu",
        short_description="Private Ivy League research university; need-blind for international applicants.",
        is_common_app=True, teaching_languages=["English"],
        major_strengths=["Liberal Arts", "Drama", "Law", "Political Science", "Economics"],
        aid_type="Need-based (need-blind for internationals)", aid_strength=10, selectivity_score=10,
        full_ride_possible=True, full_tuition_possible=True,
        aid_notes="Need-blind for all applicants; meets 100% demonstrated need with grants.",
        funding_source_url="https://finaid.yale.edu", funding_source_title="Yale Financial Aid"),
    UniversitySeed("princeton-university", "Princeton University", "United States", "Northeast", "Princeton, NJ",
        application_system=COMMON_APP, application_source_url="https://admission.princeton.edu",
        short_description="Private Ivy League research university; need-blind for international applicants.",
        is_common_app=True, teaching_languages=["English"],
        major_strengths=["Public Policy", "Engineering", "Mathematics", "Economics", "International Relations"],
        aid_type="Need-based (need-blind for internationals)", aid_strength=10, selectivity_score=10,
        full_ride_possible=True, full_tuition_possible=True,
        aid_notes="Need-blind for all applicants; meets 100% need with grants only — no loans in aid packages.",
        funding_source_url="https://admission.princeton.edu/cost-aid",
        funding_source_title="Princeton Cost & Aid"),
    UniversitySeed("columbia-university", "Columbia University", "United States", "Northeast", "New York, NY",
        application_system=COMMON_APP, application_source_url="https://undergrad.admissions.columbia.edu",
        short_description="Private Ivy League research university in Manhattan.",
        is_common_app=True, teaching_languages=["English"],
        major_strengths=["Journalism", "Liberal Arts", "International Relations", "Engineering", "Business"],
        aid_type="Need-based (need-blind for internationals)", aid_strength=10, selectivity_score=10,
        full_ride_possible=True, full_tuition_possible=True,
        aid_notes="Need-blind for all applicants since 2022; meets 100% demonstrated need.",
        funding_source_url="https://cc-seas.financialaid.columbia.edu",
        funding_source_title="Columbia Financial Aid"),
    UniversitySeed("upenn", "University of Pennsylvania", "United States", "Northeast", "Philadelphia, PA",
        application_system=COMMON_APP, application_source_url="https://admissions.upenn.edu",
        short_description="Private Ivy League research university; home of the Wharton School.",
        is_common_app=True, teaching_languages=["English"],
        major_strengths=["Business (Wharton)", "Nursing", "Engineering", "Communication"],
        aid_type="Need-based (need-aware for internationals)", aid_strength=8, selectivity_score=9,
        full_ride_possible=True, full_tuition_possible=True,
        aid_notes="Need-aware for international applicants but meets 100% demonstrated need with grants.",
        funding_source_url="https://srfs.upenn.edu", funding_source_title="Penn Student Financial Services"),
    UniversitySeed("cornell-university", "Cornell University", "United States", "Northeast", "Ithaca, NY",
        application_system=COMMON_APP, application_source_url="https://admissions.cornell.edu",
        short_description="Private Ivy League research university with statutory contract colleges.",
        is_common_app=True, teaching_languages=["English"],
        major_strengths=["Engineering", "Hotel Administration", "Agriculture & Life Sciences", "Architecture"],
        aid_type="Need-based (need-aware for internationals)", aid_strength=8, selectivity_score=9,
        full_ride_possible=True, full_tuition_possible=True,
        aid_notes="Need-aware for international applicants; meets 100% demonstrated need.",
        funding_source_url="https://finaid.cornell.edu", funding_source_title="Cornell Financial Aid"),
    UniversitySeed("brown-university", "Brown University", "United States", "Northeast", "Providence, RI",
        application_system=COMMON_APP, application_source_url="https://admission.brown.edu",
        short_description="Private Ivy League research university known for the Open Curriculum.",
        is_common_app=True, teaching_languages=["English"],
        major_strengths=["Liberal Arts", "Computer Science", "International Relations", "Public Health"],
        aid_type="Need-based (need-blind for internationals as of 2025-26)", aid_strength=9, selectivity_score=10,
        full_ride_possible=True, full_tuition_possible=True,
        aid_notes="Need-blind for international undergraduates starting with the class of 2029; meets 100% demonstrated need.",
        funding_source_url="https://www.brown.edu/about/administration/financial-aid",
        funding_source_title="Brown Financial Aid"),
    UniversitySeed("dartmouth-college", "Dartmouth College", "United States", "Northeast", "Hanover, NH",
        application_system=COMMON_APP, application_source_url="https://admissions.dartmouth.edu",
        short_description="Private Ivy League liberal-arts-focused research university.",
        is_common_app=True, teaching_languages=["English"],
        major_strengths=["Liberal Arts", "Government", "Engineering", "Economics"],
        aid_type="Need-based (need-blind for internationals as of 2022)", aid_strength=10, selectivity_score=9,
        full_ride_possible=True, full_tuition_possible=True,
        aid_notes="Need-blind admissions for all applicants since 2022; meets 100% demonstrated need.",
        funding_source_url="https://admissions.dartmouth.edu/financial-aid",
        funding_source_title="Dartmouth Financial Aid"),

    # MIT / Stanford / Caltech / UChicago / etc.
    UniversitySeed("mit", "Massachusetts Institute of Technology", "United States", "Northeast", "Cambridge, MA",
        application_system="Direct (MIT App)",
        application_source_url="https://mitadmissions.org/apply/",
        short_description="Private STEM-focused research university; need-blind for international applicants.",
        is_common_app=False, teaching_languages=["English"],
        major_strengths=["Engineering", "Computer Science", "Mathematics", "Physics", "Economics"],
        aid_type="Need-based (need-blind for internationals)", aid_strength=10, selectivity_score=10,
        full_ride_possible=True, full_tuition_possible=True,
        aid_notes="Need-blind for all applicants worldwide; meets 100% demonstrated need with grants.",
        funding_source_url="https://sfs.mit.edu", funding_source_title="MIT Student Financial Services"),
    UniversitySeed("stanford-university", "Stanford University", "United States", "West", "Stanford, CA",
        application_system=COMMON_APP, application_source_url="https://admission.stanford.edu",
        short_description="Private research university in Silicon Valley.",
        is_common_app=True, teaching_languages=["English"],
        major_strengths=["Computer Science", "Engineering", "Business", "Biology", "Education"],
        aid_type="Need-based (need-aware for internationals)", aid_strength=8, selectivity_score=10,
        full_ride_possible=True, full_tuition_possible=True,
        aid_notes="Need-aware for international applicants; meets 100% demonstrated need for admitted students.",
        funding_source_url="https://financialaid.stanford.edu",
        funding_source_title="Stanford Financial Aid"),
    UniversitySeed("caltech", "California Institute of Technology", "United States", "West", "Pasadena, CA",
        application_system=COMMON_APP, application_source_url="https://admissions.caltech.edu",
        short_description="Small private STEM research university.",
        is_common_app=True, teaching_languages=["English"],
        major_strengths=["Physics", "Engineering", "Computer Science", "Mathematics", "Astronomy"],
        aid_type="Need-based (need-aware for internationals)", aid_strength=8, selectivity_score=10,
        full_ride_possible=True, full_tuition_possible=True,
        aid_notes="Need-aware for international applicants; meets 100% demonstrated need.",
        funding_source_url="https://finaid.caltech.edu", funding_source_title="Caltech Financial Aid"),
    UniversitySeed("uchicago", "University of Chicago", "United States", "Midwest", "Chicago, IL",
        application_system=COMMON_APP, application_source_url="https://collegeadmissions.uchicago.edu",
        short_description="Private research university known for rigorous academics and the Core curriculum.",
        is_common_app=True, teaching_languages=["English"],
        major_strengths=["Economics", "Mathematics", "Political Science", "Public Policy", "Liberal Arts"],
        aid_type="Need-based + merit", aid_strength=8, selectivity_score=9,
        full_ride_possible=True, full_tuition_possible=True,
        aid_notes="Meets 100% demonstrated need for admitted international students; additional merit awards available.",
        funding_source_url="https://collegeadmissions.uchicago.edu/aid",
        funding_source_title="UChicago Financial Aid"),
    UniversitySeed("northwestern-university", "Northwestern University", "United States", "Midwest", "Evanston, IL",
        application_system=COMMON_APP, application_source_url="https://admissions.northwestern.edu",
        short_description="Private research university near Chicago; strong in journalism and engineering.",
        is_common_app=True, teaching_languages=["English"],
        major_strengths=["Journalism (Medill)", "Engineering", "Theatre", "Economics", "Communication"],
        aid_type="Need-based (need-aware for internationals)", aid_strength=8, selectivity_score=9,
        full_ride_possible=True, full_tuition_possible=True,
        aid_notes="Need-aware for international applicants; meets 100% demonstrated need with grants.",
        funding_source_url="https://undergradaid.northwestern.edu",
        funding_source_title="Northwestern Financial Aid"),
    UniversitySeed("duke-university", "Duke University", "United States", "South", "Durham, NC",
        application_system=COMMON_APP, application_source_url="https://admissions.duke.edu",
        short_description="Private research university in Research Triangle.",
        is_common_app=True, teaching_languages=["English"],
        major_strengths=["Public Policy", "Engineering", "Medicine", "Economics", "Public Health"],
        aid_type="Need-based + merit (Robertson, A.B. Duke)", aid_strength=8, selectivity_score=9,
        full_ride_possible=True, full_tuition_possible=True,
        aid_notes="Need-aware for international applicants; meets 100% demonstrated need.",
        funding_source_url="https://financialaid.duke.edu",
        funding_source_title="Duke Financial Aid"),
    UniversitySeed("johns-hopkins", "Johns Hopkins University", "United States", "Mid-Atlantic", "Baltimore, MD",
        application_system=COMMON_APP, application_source_url="https://apply.jhu.edu",
        short_description="Private research university; the original American research university.",
        is_common_app=True, teaching_languages=["English"],
        major_strengths=["Public Health", "Biomedical Engineering", "International Studies", "Medicine", "Neuroscience"],
        aid_type="Need-based (need-blind for internationals as of 2025-26)", aid_strength=9, selectivity_score=9,
        full_ride_possible=True, full_tuition_possible=True,
        aid_notes="Need-blind for international undergraduates starting class of 2030; meets 100% need.",
        funding_source_url="https://finaid.jhu.edu", funding_source_title="JHU Financial Aid"),
    UniversitySeed("vanderbilt-university", "Vanderbilt University", "United States", "South", "Nashville, TN",
        application_system=COMMON_APP, application_source_url="https://admissions.vanderbilt.edu",
        short_description="Private research university with prominent merit aid (Ingram, Cornelius Vanderbilt).",
        is_common_app=True, teaching_languages=["English"],
        major_strengths=["Engineering", "Education (Peabody)", "Music (Blair)", "Medicine"],
        aid_type="Need-based + merit (Cornelius Vanderbilt, Ingram)", aid_strength=8, selectivity_score=9,
        full_ride_possible=True, full_tuition_possible=True,
        aid_notes="Need-aware for internationals; meets 100% demonstrated need; merit scholarships available to all applicants.",
        funding_source_url="https://www.vanderbilt.edu/financialaid/",
        funding_source_title="Vanderbilt Financial Aid"),
    UniversitySeed("rice-university", "Rice University", "United States", "South", "Houston, TX",
        application_system=COMMON_APP, application_source_url="https://admission.rice.edu",
        short_description="Mid-size private research university with residential college system.",
        is_common_app=True, teaching_languages=["English"],
        major_strengths=["Engineering", "Architecture", "Music (Shepherd)", "Natural Sciences"],
        aid_type="Need-based + merit (Trustee Distinguished)", aid_strength=8, selectivity_score=9,
        full_ride_possible=True, full_tuition_possible=True,
        aid_notes="Need-aware for international applicants; meets 100% demonstrated need.",
        funding_source_url="https://financialaid.rice.edu",
        funding_source_title="Rice Financial Aid"),
    UniversitySeed("washu-st-louis", "Washington University in St. Louis", "United States", "Midwest", "St. Louis, MO",
        application_system=COMMON_APP, application_source_url="https://wustl.edu/admissions/",
        short_description="Private research university with strong programs in medicine and architecture.",
        is_common_app=True, teaching_languages=["English"],
        major_strengths=["Medicine", "Architecture", "Engineering", "Business (Olin)", "Social Work"],
        aid_type="Need-based + merit (Danforth, Ervin)", aid_strength=8, selectivity_score=8,
        full_ride_possible=True, full_tuition_possible=True,
        aid_notes="Need-aware for international applicants; meets 100% demonstrated need from class of 2024.",
        funding_source_url="https://financialaid.wustl.edu",
        funding_source_title="WashU Financial Aid"),
    UniversitySeed("emory-university", "Emory University", "United States", "South", "Atlanta, GA",
        application_system=COMMON_APP, application_source_url="https://apply.emory.edu",
        short_description="Private research university with strong public-health and business programs.",
        is_common_app=True, teaching_languages=["English"],
        major_strengths=["Public Health", "Business (Goizueta)", "Nursing", "Pre-Medicine", "Liberal Arts"],
        aid_type="Need-based + merit (Emory Scholars)", aid_strength=7, selectivity_score=8,
        full_tuition_possible=True,
        aid_notes="Need-aware for internationals; meets 100% demonstrated need for first-year admits.",
        funding_source_url="https://apply.emory.edu/cost-aid/",
        funding_source_title="Emory Cost & Aid"),
    UniversitySeed("notre-dame", "University of Notre Dame", "United States", "Midwest", "Notre Dame, IN",
        application_system=COMMON_APP, application_source_url="https://admissions.nd.edu",
        short_description="Private Catholic research university.",
        is_common_app=True, teaching_languages=["English"],
        major_strengths=["Business (Mendoza)", "Engineering", "Theology", "Arts and Letters", "Architecture"],
        aid_type="Need-based + merit", aid_strength=7, selectivity_score=8,
        full_ride_possible=True, full_tuition_possible=True,
        aid_notes="Need-aware for international applicants; meets 100% demonstrated need.",
        funding_source_url="https://financialaid.nd.edu",
        funding_source_title="Notre Dame Financial Aid"),
    UniversitySeed("georgetown-university", "Georgetown University", "United States", "Mid-Atlantic", "Washington, DC",
        application_system="Direct (Georgetown App)",
        application_source_url="https://uadmissions.georgetown.edu",
        short_description="Private Catholic research university; strong in international affairs.",
        teaching_languages=["English"],
        major_strengths=["International Relations (SFS)", "Government", "Law", "Public Policy", "Business (McDonough)"],
        aid_type="Need-based", aid_strength=7, selectivity_score=8,
        full_tuition_possible=True,
        aid_notes="Need-aware for international applicants; meets 100% demonstrated need for admitted students.",
        funding_source_url="https://finaid.georgetown.edu",
        funding_source_title="Georgetown Financial Aid"),
    UniversitySeed("usc", "University of Southern California", "United States", "West", "Los Angeles, CA",
        application_system=COMMON_APP, application_source_url="https://admission.usc.edu",
        short_description="Private research university; strong arts, business, and engineering.",
        is_common_app=True, teaching_languages=["English"],
        major_strengths=["Cinematic Arts", "Business (Marshall)", "Engineering (Viterbi)", "Communication"],
        aid_type="Need-based + merit (Trustee, Presidential)", aid_strength=7, selectivity_score=8,
        full_tuition_possible=True,
        aid_notes="Need-aware for international applicants; merit scholarships available; trustees can cover full tuition.",
        funding_source_url="https://financialaid.usc.edu",
        funding_source_title="USC Financial Aid"),
    UniversitySeed("nyu", "New York University", "United States", "Northeast", "New York, NY",
        application_system=COMMON_APP, application_source_url="https://www.nyu.edu/admissions",
        short_description="Large private research university with global campuses.",
        is_common_app=True, teaching_languages=["English"],
        major_strengths=["Business (Stern)", "Liberal Arts", "Tisch (Arts)", "Politics", "Mathematics"],
        aid_type="Need-based + merit", aid_strength=6, selectivity_score=8,
        full_tuition_possible=True,
        aid_notes="International aid limited; full Stern Scholarship and Presidential Honors available.",
        funding_source_url="https://www.nyu.edu/admissions/financial-aid-and-scholarships.html",
        funding_source_title="NYU Financial Aid"),
    UniversitySeed("boston-university", "Boston University", "United States", "Northeast", "Boston, MA",
        application_system=COMMON_APP, application_source_url="https://www.bu.edu/admissions/",
        short_description="Large private research university along the Charles River.",
        is_common_app=True, teaching_languages=["English"],
        major_strengths=["Business (Questrom)", "Communication", "Engineering", "International Relations"],
        aid_type="Need-based + merit (Trustee, Presidential)", aid_strength=6, selectivity_score=7,
        aid_notes="Limited need-based aid for internationals; merit scholarships available to all applicants.",
        funding_source_url="https://www.bu.edu/admissions/tuition-aid/scholarships-financial-aid/",
        funding_source_title="BU Financial Aid"),
    UniversitySeed("carnegie-mellon", "Carnegie Mellon University", "United States", "Mid-Atlantic", "Pittsburgh, PA",
        application_system=COMMON_APP, application_source_url="https://www.cmu.edu/admission/",
        short_description="Private research university; strong in computer science, engineering, and arts.",
        is_common_app=True, teaching_languages=["English"],
        major_strengths=["Computer Science", "Drama", "Engineering", "Design", "Public Policy"],
        aid_type="Need-based + merit", aid_strength=7, selectivity_score=9,
        full_tuition_possible=True,
        aid_notes="Need-aware for internationals; meets demonstrated need for admitted students.",
        funding_source_url="https://www.cmu.edu/sfs/financial-aid/",
        funding_source_title="CMU Financial Aid"),

    # University of California system
    UniversitySeed("uc-berkeley", "University of California, Berkeley", "United States", "West", "Berkeley, CA",
        application_system="UC Application",
        application_source_url="https://admission.universityofcalifornia.edu/how-to-apply/applying-as-a-freshman/",
        short_description="Flagship public research university of the UC system.",
        teaching_languages=["English"],
        major_strengths=["Computer Science", "Engineering", "Economics", "Political Science", "Environmental Science"],
        aid_type="Limited international aid; merit scholarships", aid_strength=4, selectivity_score=8,
        aid_notes="UC schools offer little institutional aid to international undergraduates; explore Regents Scholarships and external funding.",
        funding_source_url="https://financialaid.berkeley.edu/types-aid/scholarships/",
        funding_source_title="UC Berkeley Scholarships"),
    UniversitySeed("ucla", "University of California, Los Angeles", "United States", "West", "Los Angeles, CA",
        application_system="UC Application",
        application_source_url="https://admission.universityofcalifornia.edu/how-to-apply/applying-as-a-freshman/",
        short_description="Public research university; flagship UC campus in Southern California.",
        teaching_languages=["English"],
        major_strengths=["Film", "Psychology", "Engineering", "Business Economics", "Biology"],
        aid_type="Limited international aid", aid_strength=4, selectivity_score=8,
        aid_notes="Very limited institutional aid for international students; merit scholarships are competitive.",
        funding_source_url="https://www.financialaid.ucla.edu",
        funding_source_title="UCLA Financial Aid"),
    UniversitySeed("uc-san-diego", "University of California, San Diego", "United States", "West", "La Jolla, CA",
        application_system="UC Application",
        teaching_languages=["English"],
        major_strengths=["Engineering", "Biological Sciences", "Computer Science", "Economics", "Oceanography"],
        aid_type="Limited international aid", aid_strength=4, selectivity_score=7),
    UniversitySeed("uc-irvine", "University of California, Irvine", "United States", "West", "Irvine, CA",
        application_system="UC Application",
        teaching_languages=["English"],
        major_strengths=["Computer Science", "Engineering", "Biology", "Business"],
        aid_type="Limited international aid", aid_strength=4, selectivity_score=6),
    UniversitySeed("uc-santa-barbara", "University of California, Santa Barbara", "United States", "West", "Santa Barbara, CA",
        application_system="UC Application",
        teaching_languages=["English"],
        major_strengths=["Engineering", "Physics", "Environmental Science", "Economics", "Liberal Arts"],
        aid_type="Limited international aid", aid_strength=4, selectivity_score=6),
    UniversitySeed("uc-davis", "University of California, Davis", "United States", "West", "Davis, CA",
        application_system="UC Application",
        teaching_languages=["English"],
        major_strengths=["Veterinary Medicine", "Agriculture", "Engineering", "Biological Sciences"],
        aid_type="Limited international aid", aid_strength=4, selectivity_score=5),
    UniversitySeed("uc-santa-cruz", "University of California, Santa Cruz", "United States", "West", "Santa Cruz, CA",
        application_system="UC Application",
        teaching_languages=["English"],
        major_strengths=["Environmental Studies", "Astronomy", "Computer Science", "Linguistics"],
        aid_type="Limited international aid", aid_strength=4, selectivity_score=5),
    UniversitySeed("uc-riverside", "University of California, Riverside", "United States", "West", "Riverside, CA",
        application_system="UC Application",
        teaching_languages=["English"],
        major_strengths=["Engineering", "Business", "Biology", "Creative Writing"],
        aid_type="Limited international aid", aid_strength=4, selectivity_score=4),
    UniversitySeed("uc-merced", "University of California, Merced", "United States", "West", "Merced, CA",
        application_system="UC Application",
        teaching_languages=["English"],
        major_strengths=["Engineering", "Natural Sciences", "Sustainability"],
        aid_type="Limited international aid", aid_strength=4, selectivity_score=3),

    # State flagships
    UniversitySeed("u-michigan", "University of Michigan, Ann Arbor", "United States", "Midwest", "Ann Arbor, MI",
        application_system=COMMON_APP, is_common_app=True, teaching_languages=["English"],
        application_source_url="https://admissions.umich.edu",
        major_strengths=["Engineering", "Business (Ross)", "Information", "Public Health", "Music"],
        aid_type="Limited international aid; merit scholarships", aid_strength=4, selectivity_score=7),
    UniversitySeed("unc-chapel-hill", "University of North Carolina, Chapel Hill", "United States", "South", "Chapel Hill, NC",
        application_system=COMMON_APP, is_common_app=True, teaching_languages=["English"],
        major_strengths=["Public Health", "Journalism", "Business (Kenan-Flagler)", "Pharmacy"],
        aid_type="Limited international aid (Morehead-Cain, Robertson)", aid_strength=5, selectivity_score=7,
        full_ride_possible=True,
        aid_notes="Morehead-Cain and Robertson Scholars Programs offer full-ride scholarships open to international applicants.",
        funding_source_url="https://moreheadcain.org",
        funding_source_title="Morehead-Cain Foundation"),
    UniversitySeed("uva", "University of Virginia", "United States", "Mid-Atlantic", "Charlottesville, VA",
        application_system=COMMON_APP, is_common_app=True, teaching_languages=["English"],
        major_strengths=["Public Policy (Batten)", "Business (McIntire)", "Engineering", "Liberal Arts"],
        aid_type="Need-based; merit (Jefferson)", aid_strength=6, selectivity_score=7,
        full_ride_possible=True, full_tuition_possible=True,
        aid_notes="Need-aware for internationals; meets full need for admitted students. Jefferson Scholars cover full cost.",
        funding_source_url="https://www.jeffersonscholars.org",
        funding_source_title="Jefferson Scholars Foundation"),
    UniversitySeed("georgia-tech", "Georgia Institute of Technology", "United States", "South", "Atlanta, GA",
        application_system=COMMON_APP, is_common_app=True, teaching_languages=["English"],
        major_strengths=["Engineering", "Computer Science", "Industrial Design", "Architecture"],
        aid_type="Limited international aid", aid_strength=4, selectivity_score=7,
        application_source_url="https://admission.gatech.edu"),
    UniversitySeed("ut-austin", "University of Texas at Austin", "United States", "South", "Austin, TX",
        application_system="ApplyTexas",
        teaching_languages=["English"],
        major_strengths=["Engineering (Cockrell)", "Business (McCombs)", "Communications (Moody)", "Computer Science"],
        aid_type="Limited international aid; few merit awards", aid_strength=3, selectivity_score=7),
    UniversitySeed("u-washington", "University of Washington", "United States", "West", "Seattle, WA",
        application_system=COMMON_APP, is_common_app=True, teaching_languages=["English"],
        major_strengths=["Computer Science (Allen)", "Engineering", "Public Health", "Nursing"],
        aid_type="Limited international aid", aid_strength=3, selectivity_score=6),
    UniversitySeed("u-wisconsin-madison", "University of Wisconsin-Madison", "United States", "Midwest", "Madison, WI",
        application_system=COMMON_APP, is_common_app=True, teaching_languages=["English"],
        major_strengths=["Engineering", "Biological Sciences", "Communications", "Public Affairs"],
        aid_type="Limited international aid", aid_strength=3, selectivity_score=6),
    UniversitySeed("u-illinois-urbana", "University of Illinois Urbana-Champaign", "United States", "Midwest", "Urbana, IL",
        application_system="Coalition / Direct",
        teaching_languages=["English"],
        major_strengths=["Engineering", "Computer Science", "Business (Gies)", "Agriculture"],
        aid_type="Limited international aid", aid_strength=3, selectivity_score=6),
    UniversitySeed("u-florida", "University of Florida", "United States", "South", "Gainesville, FL",
        application_system="Coalition / SSAR",
        teaching_languages=["English"],
        major_strengths=["Engineering", "Business (Warrington)", "Agriculture", "Journalism"],
        aid_type="Limited international aid", aid_strength=3, selectivity_score=6),
    UniversitySeed("u-maryland", "University of Maryland, College Park", "United States", "Mid-Atlantic", "College Park, MD",
        application_system=COMMON_APP, is_common_app=True, teaching_languages=["English"],
        major_strengths=["Engineering (Clark)", "Computer Science", "Business (Smith)", "Public Policy"],
        aid_type="Limited international aid", aid_strength=3, selectivity_score=5),
    UniversitySeed("ohio-state", "Ohio State University", "United States", "Midwest", "Columbus, OH",
        application_system=COMMON_APP, is_common_app=True, teaching_languages=["English"],
        major_strengths=["Engineering", "Business (Fisher)", "Agriculture", "Public Affairs"],
        aid_type="Merit scholarships; limited need-based aid", aid_strength=4, selectivity_score=5),
    UniversitySeed("penn-state", "Pennsylvania State University", "United States", "Mid-Atlantic", "University Park, PA",
        application_system="Direct",
        teaching_languages=["English"],
        major_strengths=["Engineering", "Business (Smeal)", "Communications", "Earth Sciences"],
        aid_type="Limited international aid", aid_strength=3, selectivity_score=5),
    UniversitySeed("purdue-university", "Purdue University", "United States", "Midwest", "West Lafayette, IN",
        application_system=COMMON_APP, is_common_app=True, teaching_languages=["English"],
        major_strengths=["Engineering", "Computer Science", "Aviation", "Pharmacy"],
        aid_type="Limited international aid", aid_strength=3, selectivity_score=5),
    UniversitySeed("u-minnesota", "University of Minnesota, Twin Cities", "United States", "Midwest", "Minneapolis, MN",
        application_system="Direct",
        teaching_languages=["English"],
        major_strengths=["Engineering", "Business (Carlson)", "Public Health", "Education"],
        aid_type="Limited international aid; merit", aid_strength=3, selectivity_score=4),
    UniversitySeed("rutgers-new-brunswick", "Rutgers University, New Brunswick", "United States", "Northeast", "New Brunswick, NJ",
        application_system="Direct",
        teaching_languages=["English"],
        major_strengths=["Pharmacy", "Engineering", "Business", "Information"],
        aid_type="Limited international aid", aid_strength=3, selectivity_score=4),

    # Liberal arts colleges
    UniversitySeed("williams-college", "Williams College", "United States", "Northeast", "Williamstown, MA",
        application_system=COMMON_APP, is_common_app=True, teaching_languages=["English"],
        application_source_url="https://admission.williams.edu",
        major_strengths=["Liberal Arts", "Economics", "Political Science", "Art History"],
        aid_type="Need-based (need-blind for internationals)", aid_strength=10, selectivity_score=9,
        full_ride_possible=True, full_tuition_possible=True,
        aid_notes="Need-blind for all applicants; meets 100% demonstrated need with grants only.",
        funding_source_url="https://financial-aid.williams.edu"),
    UniversitySeed("amherst-college", "Amherst College", "United States", "Northeast", "Amherst, MA",
        application_system=COMMON_APP, is_common_app=True, teaching_languages=["English"],
        major_strengths=["Liberal Arts", "Economics", "Mathematics", "English"],
        aid_type="Need-based (need-blind for internationals)", aid_strength=10, selectivity_score=9,
        full_ride_possible=True, full_tuition_possible=True,
        aid_notes="Need-blind for all applicants since 1999; meets 100% demonstrated need with grants only.",
        funding_source_url="https://www.amherst.edu/admission/financialaid"),
    UniversitySeed("swarthmore-college", "Swarthmore College", "United States", "Mid-Atlantic", "Swarthmore, PA",
        application_system=COMMON_APP, is_common_app=True, teaching_languages=["English"],
        major_strengths=["Liberal Arts", "Engineering", "Mathematics", "Political Science"],
        aid_type="Need-based (need-blind for internationals)", aid_strength=10, selectivity_score=9,
        full_ride_possible=True, full_tuition_possible=True,
        aid_notes="Need-blind for all applicants; meets 100% demonstrated need with grants only.",
        funding_source_url="https://www.swarthmore.edu/financial-aid"),
    UniversitySeed("pomona-college", "Pomona College", "United States", "West", "Claremont, CA",
        application_system=COMMON_APP, is_common_app=True, teaching_languages=["English"],
        major_strengths=["Liberal Arts", "Economics", "Computer Science", "Public Policy"],
        aid_type="Need-based (need-blind for internationals)", aid_strength=10, selectivity_score=9,
        full_ride_possible=True, full_tuition_possible=True,
        aid_notes="Need-blind for all applicants; meets 100% demonstrated need.",
        funding_source_url="https://www.pomona.edu/admissions/financial-aid"),
    UniversitySeed("wellesley-college", "Wellesley College", "United States", "Northeast", "Wellesley, MA",
        application_system=COMMON_APP, is_common_app=True, teaching_languages=["English"],
        major_strengths=["Liberal Arts", "Political Science", "Economics", "Sciences (Pre-Med)"],
        aid_type="Need-based", aid_strength=8, selectivity_score=8,
        full_ride_possible=True, full_tuition_possible=True,
        aid_notes="Women's college; need-aware for internationals; meets 100% demonstrated need.",
        funding_source_url="https://www.wellesley.edu/sfs"),
    UniversitySeed("bowdoin-college", "Bowdoin College", "United States", "Northeast", "Brunswick, ME",
        application_system=COMMON_APP, is_common_app=True, teaching_languages=["English"],
        major_strengths=["Liberal Arts", "Government", "Environmental Studies", "Mathematics"],
        aid_type="Need-based (need-blind for internationals)", aid_strength=10, selectivity_score=9,
        full_ride_possible=True, full_tuition_possible=True,
        aid_notes="Need-blind for all applicants; meets 100% demonstrated need with grants only (no loans).",
        funding_source_url="https://www.bowdoin.edu/student-aid"),
    UniversitySeed("carleton-college", "Carleton College", "United States", "Midwest", "Northfield, MN",
        application_system=COMMON_APP, is_common_app=True, teaching_languages=["English"],
        major_strengths=["Liberal Arts", "Mathematics", "Computer Science", "Economics"],
        aid_type="Need-based + merit", aid_strength=8, selectivity_score=8,
        full_ride_possible=True, full_tuition_possible=True,
        aid_notes="Need-aware for international applicants; meets 100% demonstrated need."),
    UniversitySeed("middlebury-college", "Middlebury College", "United States", "Northeast", "Middlebury, VT",
        application_system=COMMON_APP, is_common_app=True, teaching_languages=["English"],
        major_strengths=["Liberal Arts", "International Studies", "Languages", "Environmental Studies"],
        aid_type="Need-based + merit", aid_strength=7, selectivity_score=8,
        full_ride_possible=True, full_tuition_possible=True,
        aid_notes="Need-aware for international applicants; meets 100% demonstrated need."),
    UniversitySeed("claremont-mckenna", "Claremont McKenna College", "United States", "West", "Claremont, CA",
        application_system=COMMON_APP, is_common_app=True, teaching_languages=["English"],
        major_strengths=["Economics", "Government", "International Relations", "Public Policy"],
        aid_type="Need-based", aid_strength=7, selectivity_score=8,
        aid_notes="Need-aware for international applicants; meets 100% demonstrated need."),
    UniversitySeed("hamilton-college", "Hamilton College", "United States", "Northeast", "Clinton, NY",
        application_system=COMMON_APP, is_common_app=True, teaching_languages=["English"],
        major_strengths=["Liberal Arts", "Government", "Economics", "Writing"],
        aid_type="Need-based + merit", aid_strength=7, selectivity_score=8,
        aid_notes="Need-aware for international applicants; meets demonstrated need."),

    # HBCUs / others
    UniversitySeed("howard-university", "Howard University", "United States", "Mid-Atlantic", "Washington, DC",
        application_system=COMMON_APP, is_common_app=True, teaching_languages=["English"],
        major_strengths=["Communications", "Business", "Health Sciences", "Law"],
        aid_type="Need-based + merit", aid_strength=5, selectivity_score=6,
        aid_notes="Largest HBCU by enrollment; merit and Capstone scholarships available."),
    UniversitySeed("spelman-college", "Spelman College", "United States", "South", "Atlanta, GA",
        application_system=COMMON_APP, is_common_app=True, teaching_languages=["English"],
        major_strengths=["Liberal Arts", "Sciences", "Education"],
        aid_type="Need-based + merit", aid_strength=5, selectivity_score=6,
        aid_notes="Historically Black women's college; competitive merit awards available."),
    UniversitySeed("morehouse-college", "Morehouse College", "United States", "South", "Atlanta, GA",
        application_system=COMMON_APP, is_common_app=True, teaching_languages=["English"],
        major_strengths=["Liberal Arts", "Business", "Pre-Medicine"],
        aid_type="Need-based + merit", aid_strength=5, selectivity_score=5,
        aid_notes="Historically Black men's college; merit awards available."),
]


# ---------------------------------------------------------------------------
# United Kingdom (15)
# ---------------------------------------------------------------------------
UK: list[UniversitySeed] = [
    UniversitySeed("oxford", "University of Oxford", "United Kingdom", "England", "Oxford",
        application_system=UCAS, application_source_url="https://www.ox.ac.uk/admissions/undergraduate",
        short_description="Collegiate research university; one of the oldest English-speaking universities.",
        teaching_languages=["English"],
        major_strengths=["PPE", "Mathematics", "Physics", "Law", "Classics", "Medicine"],
        education_years_required=12,
        school_years_note="UK applicants typically apply with A-Levels (3 A* / A typical); IB 38-40 with 6/7 in HL subjects expected.",
        aid_type="Need-based (Reach Oxford); Rhodes; merit", aid_strength=6, selectivity_score=10,
        full_ride_possible=True,
        aid_notes="Reach Oxford Scholarship covers full tuition + living for low-income international students from selected countries.",
        funding_source_url="https://www.ox.ac.uk/admissions/undergraduate/fees-and-funding/oxford-support",
        funding_source_title="University of Oxford Fees and Funding"),
    UniversitySeed("cambridge", "University of Cambridge", "United Kingdom", "England", "Cambridge",
        application_system=UCAS, application_source_url="https://www.undergraduate.study.cam.ac.uk",
        short_description="Collegiate research university; second oldest in the English-speaking world.",
        teaching_languages=["English"],
        major_strengths=["Mathematics", "Engineering", "Natural Sciences", "Medicine", "Computer Science"],
        school_years_note="UCAS deadline October 16 for Oxbridge; supplementary Cambridge My Application required.",
        aid_type="Need-based; Cambridge Trust; Gates Cambridge (graduate)",
        aid_strength=6, selectivity_score=10,
        full_ride_possible=True,
        aid_notes="Cambridge Trust offers needs-based scholarships to undergraduate internationals; Gates Cambridge funds graduate study.",
        funding_source_url="https://www.cambridgetrust.org",
        funding_source_title="Cambridge Trust"),
    UniversitySeed("imperial-college", "Imperial College London", "United Kingdom", "England", "London",
        application_system=UCAS, application_source_url="https://www.imperial.ac.uk/study/apply/undergraduate/",
        short_description="STEM-focused public research university in central London.",
        teaching_languages=["English"],
        major_strengths=["Engineering", "Computer Science", "Medicine", "Mathematics", "Physics"],
        aid_type="Limited need-based aid for internationals; President's Undergraduate Scholarships",
        aid_strength=4, selectivity_score=9),
    UniversitySeed("ucl", "University College London", "United Kingdom", "England", "London",
        application_system=UCAS, teaching_languages=["English"],
        major_strengths=["Architecture (Bartlett)", "Economics", "Medicine", "Law", "Computer Science"],
        aid_type="Limited; Global Undergraduate Scholarship", aid_strength=4, selectivity_score=8),
    UniversitySeed("lse", "London School of Economics and Political Science", "United Kingdom", "England", "London",
        application_system=UCAS, teaching_languages=["English"],
        major_strengths=["Economics", "Government", "International Relations", "Finance", "Sociology"],
        aid_type="Need-based (LSE Undergraduate Support Scheme)", aid_strength=5, selectivity_score=9),
    UniversitySeed("edinburgh", "University of Edinburgh", "United Kingdom", "Scotland", "Edinburgh",
        application_system=UCAS, teaching_languages=["English"],
        major_strengths=["Medicine", "Veterinary Medicine", "AI / Informatics", "Law", "Linguistics"],
        aid_type="Merit + need-based (Edinburgh Global)", aid_strength=4, selectivity_score=7),
    UniversitySeed("kings-college-london", "King's College London", "United Kingdom", "England", "London",
        application_system=UCAS, teaching_languages=["English"],
        major_strengths=["Medicine", "Law", "Nursing", "International Relations"],
        aid_type="Limited; King's Living Bursary (UK only)", aid_strength=3, selectivity_score=7),
    UniversitySeed("manchester", "University of Manchester", "United Kingdom", "England", "Manchester",
        application_system=UCAS, teaching_languages=["English"],
        major_strengths=["Engineering", "Computer Science", "Materials", "Medicine"],
        aid_type="Merit + Manchester Bursary (UK)", aid_strength=3, selectivity_score=6),
    UniversitySeed("bristol", "University of Bristol", "United Kingdom", "England", "Bristol",
        application_system=UCAS, teaching_languages=["English"],
        major_strengths=["Engineering", "Aerospace", "Veterinary Sciences", "Law"],
        aid_type="Merit (Think Big Scholarship)", aid_strength=4, selectivity_score=6),
    UniversitySeed("warwick", "University of Warwick", "United Kingdom", "England", "Coventry",
        application_system=UCAS, teaching_languages=["English"],
        major_strengths=["Mathematics", "Economics", "Business (WBS)", "Computer Science"],
        aid_type="Merit; Warwick Undergraduate Global Excellence Scholarship",
        aid_strength=4, selectivity_score=7),
    UniversitySeed("glasgow", "University of Glasgow", "United Kingdom", "Scotland", "Glasgow",
        application_system=UCAS, teaching_languages=["English"],
        major_strengths=["Veterinary Medicine", "Engineering", "Law", "Medicine"],
        aid_type="Merit (International Excellence)", aid_strength=3, selectivity_score=5),
    UniversitySeed("durham", "Durham University", "United Kingdom", "England", "Durham",
        application_system=UCAS, teaching_languages=["English"],
        major_strengths=["Theology", "History", "Mathematics", "Law"],
        aid_type="Merit (Durham Inspire)", aid_strength=3, selectivity_score=6),
    UniversitySeed("st-andrews", "University of St Andrews", "United Kingdom", "Scotland", "St Andrews",
        application_system=UCAS, teaching_languages=["English"],
        major_strengths=["Liberal Arts", "International Relations", "Philosophy", "English"],
        aid_type="Merit + need-based (Wardlaw)", aid_strength=4, selectivity_score=7),
    UniversitySeed("birmingham", "University of Birmingham", "United Kingdom", "England", "Birmingham",
        application_system=UCAS, teaching_languages=["English"],
        major_strengths=["Engineering", "Business", "Medicine", "Sport Science"],
        aid_type="Merit (Global Masters / Undergraduate Scholarships)",
        aid_strength=3, selectivity_score=5),
    UniversitySeed("sheffield", "University of Sheffield", "United Kingdom", "England", "Sheffield",
        application_system=UCAS, teaching_languages=["English"],
        major_strengths=["Engineering", "Architecture", "Journalism", "Materials"],
        aid_type="Merit (International Undergraduate)",
        aid_strength=3, selectivity_score=5),
]


# ---------------------------------------------------------------------------
# Continental Europe (35)
# ---------------------------------------------------------------------------
EUROPE: list[UniversitySeed] = [
    # Germany — public, low/no tuition
    UniversitySeed("tu-munich", "Technical University of Munich", "Germany", "Bavaria", "Munich",
        application_system=UNI_ASSIST,
        application_source_url="https://www.tum.de/en/studies/application",
        short_description="Public technical research university; low tuition for internationals (Bavaria adds €2k/sem from 2024).",
        teaching_languages=["English", "German"],
        major_strengths=["Engineering", "Computer Science", "Physics", "Management"],
        aid_type="Merit (Deutschlandstipendium); DAAD",
        aid_strength=5, selectivity_score=7,
        aid_notes="Most undergraduate programs taught in German; English Bachelor's limited. Bavaria reintroduced ~€2k/semester tuition for non-EU students in 2024."),
    UniversitySeed("lmu-munich", "Ludwig Maximilian University of Munich", "Germany", "Bavaria", "Munich",
        application_system=UNI_ASSIST, teaching_languages=["German", "English"],
        major_strengths=["Medicine", "Liberal Arts", "Law", "Physics"],
        aid_type="Merit (Deutschlandstipendium); DAAD", aid_strength=5, selectivity_score=6),
    UniversitySeed("heidelberg", "Heidelberg University", "Germany", "Baden-Württemberg", "Heidelberg",
        application_system=UNI_ASSIST, teaching_languages=["German", "English"],
        major_strengths=["Medicine", "Physics", "Philosophy", "Law"],
        aid_type="Baden-Württemberg charges €1,500/sem; Deutschlandstipendium",
        aid_strength=4, selectivity_score=6),
    UniversitySeed("humboldt-berlin", "Humboldt University of Berlin", "Germany", "Berlin", "Berlin",
        application_system=UNI_ASSIST, teaching_languages=["German", "English"],
        major_strengths=["Liberal Arts", "Humanities", "Sciences", "Economics"],
        aid_type="No tuition for most programs; DAAD", aid_strength=6, selectivity_score=5),
    UniversitySeed("fu-berlin", "Free University of Berlin", "Germany", "Berlin", "Berlin",
        application_system=UNI_ASSIST, teaching_languages=["German", "English"],
        major_strengths=["Political Science", "Humanities", "Sciences"],
        aid_type="No tuition for most programs; DAAD", aid_strength=6, selectivity_score=5),
    UniversitySeed("rwth-aachen", "RWTH Aachen University", "Germany", "North Rhine-Westphalia", "Aachen",
        application_system=UNI_ASSIST, teaching_languages=["German", "English"],
        major_strengths=["Engineering", "Mechanical Engineering", "Computer Science", "Materials"],
        aid_type="No tuition; semester fee only", aid_strength=6, selectivity_score=5),
    UniversitySeed("kit", "Karlsruhe Institute of Technology", "Germany", "Baden-Württemberg", "Karlsruhe",
        application_system=UNI_ASSIST, teaching_languages=["German", "English"],
        major_strengths=["Engineering", "Computer Science", "Mathematics", "Physics"],
        aid_type="€1,500/sem (Baden-Württemberg)", aid_strength=4, selectivity_score=5),
    UniversitySeed("tu-berlin", "Technical University of Berlin", "Germany", "Berlin", "Berlin",
        application_system=UNI_ASSIST, teaching_languages=["German", "English"],
        major_strengths=["Engineering", "Architecture", "Computer Science"],
        aid_type="No tuition; semester fee only", aid_strength=6, selectivity_score=5),
    UniversitySeed("uni-bonn", "University of Bonn", "Germany", "North Rhine-Westphalia", "Bonn",
        application_system=UNI_ASSIST, teaching_languages=["German", "English"],
        major_strengths=["Mathematics", "Economics", "Law", "Liberal Arts"],
        aid_type="No tuition", aid_strength=6, selectivity_score=5),
    UniversitySeed("tubingen", "University of Tübingen", "Germany", "Baden-Württemberg", "Tübingen",
        application_system=UNI_ASSIST, teaching_languages=["German", "English"],
        major_strengths=["Theology", "Philosophy", "Sciences", "Linguistics"],
        aid_type="€1,500/sem (Baden-Württemberg)", aid_strength=4, selectivity_score=5),

    # Netherlands
    UniversitySeed("tu-delft", "Delft University of Technology", "Netherlands", "South Holland", "Delft",
        application_system=STUDIE_LINK,
        application_source_url="https://www.tudelft.nl/en/education/admission-and-application",
        short_description="Public technical university; many English-taught programs.",
        teaching_languages=["English", "Dutch"],
        major_strengths=["Aerospace Engineering", "Computer Science", "Architecture", "Civil Engineering"],
        aid_type="Justus & Louise van Effen scholarship (full, very competitive)",
        aid_strength=5, selectivity_score=6),
    UniversitySeed("uva-amsterdam", "University of Amsterdam", "Netherlands", "North Holland", "Amsterdam",
        application_system=STUDIE_LINK, teaching_languages=["English", "Dutch"],
        major_strengths=["Liberal Arts", "Economics", "Communication", "Law"],
        aid_type="Amsterdam Merit Scholarship", aid_strength=4, selectivity_score=5),
    UniversitySeed("erasmus-rotterdam", "Erasmus University Rotterdam", "Netherlands", "South Holland", "Rotterdam",
        application_system=STUDIE_LINK, teaching_languages=["English", "Dutch"],
        major_strengths=["Business (RSM)", "Economics", "Public Policy", "Medicine"],
        aid_type="Holland Scholarship; Erasmus Trustfonds", aid_strength=4, selectivity_score=6),
    UniversitySeed("leiden-university", "Leiden University", "Netherlands", "South Holland", "Leiden",
        application_system=STUDIE_LINK, teaching_languages=["English", "Dutch"],
        major_strengths=["Law", "International Studies", "Astronomy", "Linguistics"],
        aid_type="Holland Scholarship; Leiden University Excellence Scholarship",
        aid_strength=4, selectivity_score=5),
    UniversitySeed("utrecht", "Utrecht University", "Netherlands", "Utrecht", "Utrecht",
        application_system=STUDIE_LINK, teaching_languages=["English", "Dutch"],
        major_strengths=["Economics", "Veterinary Medicine", "Liberal Arts", "Geosciences"],
        aid_type="UU Excellence Scholarship", aid_strength=4, selectivity_score=5),
    UniversitySeed("eindhoven-tue", "Eindhoven University of Technology", "Netherlands", "North Brabant", "Eindhoven",
        application_system=STUDIE_LINK, teaching_languages=["English", "Dutch"],
        major_strengths=["Engineering", "Computer Science", "Industrial Design"],
        aid_type="TU/e Honors / Holland Scholarship", aid_strength=4, selectivity_score=5),
    UniversitySeed("groningen", "University of Groningen", "Netherlands", "Groningen", "Groningen",
        application_system=STUDIE_LINK, teaching_languages=["English", "Dutch"],
        major_strengths=["Liberal Arts (UCG)", "Astronomy", "Sciences", "Business"],
        aid_type="Eric Bleumink Fund; Holland Scholarship", aid_strength=4, selectivity_score=5),

    # Switzerland
    UniversitySeed("eth-zurich", "ETH Zurich (Swiss Federal Institute of Technology)", "Switzerland", "Zurich", "Zurich",
        application_system=DIRECT,
        application_source_url="https://ethz.ch/en/studies/admission/application.html",
        short_description="Public STEM research university; low tuition (~€1,300/year).",
        teaching_languages=["German", "English"],
        major_strengths=["Computer Science", "Engineering", "Mathematics", "Physics", "Architecture"],
        aid_type="ETH Excellence Scholarship & Opportunity Programme (need-based)",
        aid_strength=7, selectivity_score=9,
        full_ride_possible=True,
        aid_notes="ETH-D Scholarship and Excellence Scholarship can cover full tuition + living for high-merit applicants."),
    UniversitySeed("epfl", "École Polytechnique Fédérale de Lausanne", "Switzerland", "Vaud", "Lausanne",
        application_system=DIRECT, teaching_languages=["French", "English"],
        major_strengths=["Engineering", "Computer Science", "Architecture", "Life Sciences"],
        aid_type="EPFL Excellence Fellowships",
        aid_strength=6, selectivity_score=8),
    UniversitySeed("uni-zurich", "University of Zurich", "Switzerland", "Zurich", "Zurich",
        application_system=DIRECT, teaching_languages=["German", "English"],
        major_strengths=["Medicine", "Economics", "Law", "Liberal Arts"],
        aid_type="Limited", aid_strength=3, selectivity_score=6),
    UniversitySeed("uni-st-gallen", "University of St. Gallen", "Switzerland", "St. Gallen", "St. Gallen",
        application_system=DIRECT, teaching_languages=["German", "English"],
        major_strengths=["Business", "Economics", "Law", "International Affairs"],
        aid_type="HSG Stiftung", aid_strength=4, selectivity_score=7),

    # Sweden
    UniversitySeed("kth-stockholm", "KTH Royal Institute of Technology", "Sweden", "Stockholm", "Stockholm",
        application_system=SWE_INDEX, teaching_languages=["English", "Swedish"],
        major_strengths=["Engineering", "Computer Science", "Architecture"],
        aid_type="KTH Scholarship for tuition; Swedish Institute scholarships",
        aid_strength=5, selectivity_score=6),
    UniversitySeed("stockholm-university", "Stockholm University", "Sweden", "Stockholm", "Stockholm",
        application_system=SWE_INDEX, teaching_languages=["English", "Swedish"],
        major_strengths=["Liberal Arts", "Mathematics", "Economics", "Linguistics"],
        aid_type="Limited", aid_strength=3, selectivity_score=5),
    UniversitySeed("uppsala", "Uppsala University", "Sweden", "Uppsala", "Uppsala",
        application_system=SWE_INDEX, teaching_languages=["English", "Swedish"],
        major_strengths=["Sciences", "Medicine", "Engineering", "Liberal Arts"],
        aid_type="Uppsala IPK Foundation Scholarships", aid_strength=3, selectivity_score=5),
    UniversitySeed("lund-university", "Lund University", "Sweden", "Skåne", "Lund",
        application_system=SWE_INDEX, teaching_languages=["English", "Swedish"],
        major_strengths=["Engineering", "Liberal Arts", "Medicine", "Business"],
        aid_type="Lund University Global Scholarship", aid_strength=4, selectivity_score=5),
    UniversitySeed("chalmers", "Chalmers University of Technology", "Sweden", "Västra Götaland", "Gothenburg",
        application_system=SWE_INDEX, teaching_languages=["English", "Swedish"],
        major_strengths=["Engineering", "Computer Science", "Architecture"],
        aid_type="Chalmers IPOET / Avancez Scholarships",
        aid_strength=4, selectivity_score=5),

    # France
    UniversitySeed("sciences-po", "Sciences Po", "France", "Île-de-France", "Paris",
        application_system=DIRECT,
        application_source_url="https://www.sciencespo.fr/en/admissions",
        short_description="Selective public research university focused on social sciences with the dual-degree network.",
        teaching_languages=["English", "French"],
        major_strengths=["Political Science", "International Relations", "Economics", "Public Policy", "Law"],
        aid_type="Need-based (Émile Boutmy for non-EU)",
        aid_strength=6, selectivity_score=8,
        full_tuition_possible=True,
        aid_notes="Émile Boutmy Scholarship for non-EU students can cover up to full tuition plus a living stipend."),
    UniversitySeed("ecole-polytechnique", "École Polytechnique", "France", "Île-de-France", "Palaiseau",
        application_system=DIRECT, teaching_languages=["English", "French"],
        major_strengths=["Engineering", "Mathematics", "Physics", "Computer Science"],
        aid_type="Bachelor of Science scholarships; merit-based",
        aid_strength=5, selectivity_score=8),
    UniversitySeed("ens-paris", "École Normale Supérieure (ENS) Paris", "France", "Île-de-France", "Paris",
        application_system=DIRECT, teaching_languages=["French", "English"],
        major_strengths=["Mathematics", "Physics", "Liberal Arts", "Linguistics"],
        aid_type="ENS International Selection (full stipend)",
        aid_strength=7, selectivity_score=9,
        full_ride_possible=True,
        aid_notes="ENS International Selection admits ~30 international students/year on a full stipend (Sélection Internationale)."),
    UniversitySeed("sorbonne-university", "Sorbonne University", "France", "Île-de-France", "Paris",
        application_system=DIRECT, teaching_languages=["French", "English"],
        major_strengths=["Liberal Arts", "Sciences", "Medicine"],
        aid_type="Eiffel Excellence (graduate); merit",
        aid_strength=4, selectivity_score=6),
    UniversitySeed("hec-paris", "HEC Paris", "France", "Île-de-France", "Jouy-en-Josas",
        application_system=DIRECT, teaching_languages=["English", "French"],
        major_strengths=["Business", "Management", "Finance"],
        aid_type="Excellence and merit scholarships", aid_strength=4, selectivity_score=8),

    # Denmark / Finland / Norway
    UniversitySeed("ku-copenhagen", "University of Copenhagen", "Denmark", "Capital Region", "Copenhagen",
        application_system=DIRECT, teaching_languages=["English", "Danish"],
        major_strengths=["Sciences", "Medicine", "Liberal Arts", "Economics"],
        aid_type="Danish Government Scholarships (very competitive)",
        aid_strength=4, selectivity_score=6),
    UniversitySeed("dtu", "Technical University of Denmark", "Denmark", "Capital Region", "Lyngby",
        application_system=DIRECT, teaching_languages=["English", "Danish"],
        major_strengths=["Engineering", "Computer Science", "Wind Energy"],
        aid_type="DTU Scholarships", aid_strength=4, selectivity_score=6),
    UniversitySeed("aalto-university", "Aalto University", "Finland", "Uusimaa", "Espoo",
        application_system=DIRECT, teaching_languages=["English", "Finnish"],
        major_strengths=["Engineering", "Business", "Design", "Architecture"],
        aid_type="Aalto Scholarship (50% or 100% tuition)",
        aid_strength=5, selectivity_score=6),
    UniversitySeed("helsinki", "University of Helsinki", "Finland", "Uusimaa", "Helsinki",
        application_system=DIRECT, teaching_languages=["English", "Finnish"],
        major_strengths=["Sciences", "Medicine", "Education", "Liberal Arts"],
        aid_type="Finland Scholarship; ASLA-Fulbright",
        aid_strength=4, selectivity_score=5),

    # Italy / Spain
    UniversitySeed("bocconi", "Bocconi University", "Italy", "Lombardy", "Milan",
        application_system=DIRECT, teaching_languages=["English", "Italian"],
        major_strengths=["Economics", "Business", "Finance", "Law"],
        aid_type="Need-based (Bocconi Merit / Need); ISU EDISU",
        aid_strength=6, selectivity_score=7,
        full_tuition_possible=True,
        aid_notes="Bocconi need-based aid can cover full tuition for international students with strong financial need."),
    UniversitySeed("politecnico-milano", "Politecnico di Milano", "Italy", "Lombardy", "Milan",
        application_system=DIRECT, teaching_languages=["English", "Italian"],
        major_strengths=["Engineering", "Architecture", "Design"],
        aid_type="Merit; ISU regional", aid_strength=4, selectivity_score=6),
    UniversitySeed("sapienza", "Sapienza University of Rome", "Italy", "Lazio", "Rome",
        application_system=DIRECT, teaching_languages=["Italian", "English"],
        major_strengths=["Engineering", "Architecture", "Liberal Arts", "Medicine"],
        aid_type="Sapienza scholarships; regional aid",
        aid_strength=3, selectivity_score=4),
    UniversitySeed("ie-university", "IE University", "Spain", "Madrid", "Madrid / Segovia",
        application_system=DIRECT, teaching_languages=["English", "Spanish"],
        major_strengths=["Business", "International Relations", "Communication", "Law"],
        aid_type="Merit (IE Foundation Scholarships)",
        aid_strength=5, selectivity_score=6),
]


# ---------------------------------------------------------------------------
# Asia & Hong Kong (30)
# ---------------------------------------------------------------------------
ASIA: list[UniversitySeed] = [
    # China
    UniversitySeed("tsinghua", "Tsinghua University", "China", "Beijing", "Beijing",
        application_system=DIRECT, application_source_url="https://www.tsinghua.edu.cn/en/Admissions.htm",
        short_description="Public research university; one of the C9 League schools.",
        teaching_languages=["Chinese (Mandarin)", "English"],
        major_strengths=["Engineering", "Computer Science", "Architecture", "Economics"],
        aid_type="Chinese Government Scholarship (CSC); Schwarzman (graduate)",
        aid_strength=6, selectivity_score=9,
        full_ride_possible=True,
        aid_notes="CSC Bilateral Program covers tuition + housing + stipend for international students nominated by their home country."),
    UniversitySeed("peking-university", "Peking University", "China", "Beijing", "Beijing",
        application_system=DIRECT, teaching_languages=["Chinese (Mandarin)", "English"],
        major_strengths=["Liberal Arts", "Economics (CCER)", "Medicine", "Law"],
        aid_type="CSC; Yenching Academy (graduate)", aid_strength=6, selectivity_score=9,
        full_ride_possible=True),
    UniversitySeed("fudan", "Fudan University", "China", "Shanghai", "Shanghai",
        application_system=DIRECT, teaching_languages=["Chinese (Mandarin)", "English"],
        major_strengths=["Economics", "Journalism", "International Relations", "Medicine"],
        aid_type="CSC; Fudan Scholarships", aid_strength=5, selectivity_score=7),
    UniversitySeed("sjtu", "Shanghai Jiao Tong University", "China", "Shanghai", "Shanghai",
        application_system=DIRECT, teaching_languages=["Chinese (Mandarin)", "English"],
        major_strengths=["Engineering", "Computer Science", "Medicine", "Naval Architecture"],
        aid_type="CSC; SJTU Scholarships", aid_strength=5, selectivity_score=7),
    UniversitySeed("zhejiang", "Zhejiang University", "China", "Zhejiang", "Hangzhou",
        application_system=DIRECT, teaching_languages=["Chinese (Mandarin)", "English"],
        major_strengths=["Engineering", "Computer Science", "Agriculture"],
        aid_type="CSC; Zhejiang Scholarships", aid_strength=5, selectivity_score=7),
    UniversitySeed("nanjing", "Nanjing University", "China", "Jiangsu", "Nanjing",
        application_system=DIRECT, teaching_languages=["Chinese (Mandarin)", "English"],
        major_strengths=["Liberal Arts", "Astronomy", "Chemistry", "International Studies"],
        aid_type="CSC; Nanjing Scholarships", aid_strength=4, selectivity_score=6),
    UniversitySeed("ustc", "University of Science and Technology of China", "China", "Anhui", "Hefei",
        application_system=DIRECT, teaching_languages=["Chinese (Mandarin)", "English"],
        major_strengths=["Physics", "Mathematics", "Computer Science", "Chemistry"],
        aid_type="CSC", aid_strength=5, selectivity_score=7),

    # Japan
    UniversitySeed("u-tokyo", "University of Tokyo", "Japan", "Kantō", "Tokyo",
        application_system=DIRECT,
        application_source_url="https://www.u-tokyo.ac.jp/en/prospective-students/index.html",
        short_description="Top public research university; PEAK English-medium program.",
        teaching_languages=["Japanese", "English"],
        major_strengths=["Sciences", "Engineering", "Liberal Arts (PEAK)", "Medicine"],
        aid_type="MEXT Scholarship; UTokyo Fellowship",
        aid_strength=6, selectivity_score=9,
        full_ride_possible=True,
        aid_notes="MEXT (Monbukagakusho) scholarship covers tuition + monthly stipend for international students through embassy or university recommendation."),
    UniversitySeed("kyoto-university", "Kyoto University", "Japan", "Kansai", "Kyoto",
        application_system=DIRECT, teaching_languages=["Japanese", "English"],
        major_strengths=["Sciences", "Liberal Arts", "Engineering", "Medicine"],
        aid_type="MEXT; Kyoto iUP", aid_strength=6, selectivity_score=8,
        full_ride_possible=True),
    UniversitySeed("osaka-university", "Osaka University", "Japan", "Kansai", "Osaka",
        application_system=DIRECT, teaching_languages=["Japanese", "English"],
        major_strengths=["Engineering", "Medicine", "Sciences"],
        aid_type="MEXT", aid_strength=5, selectivity_score=7),
    UniversitySeed("tohoku-university", "Tohoku University", "Japan", "Tōhoku", "Sendai",
        application_system=DIRECT, teaching_languages=["Japanese", "English"],
        major_strengths=["Engineering", "Materials", "Sciences"],
        aid_type="MEXT; FGL English-taught Bachelor", aid_strength=5, selectivity_score=6),
    UniversitySeed("titech", "Tokyo Institute of Technology", "Japan", "Kantō", "Tokyo",
        application_system=DIRECT, teaching_languages=["Japanese", "English"],
        major_strengths=["Engineering", "Computer Science", "Architecture"],
        aid_type="MEXT", aid_strength=5, selectivity_score=7),
    UniversitySeed("waseda", "Waseda University", "Japan", "Kantō", "Tokyo",
        application_system=DIRECT, teaching_languages=["Japanese", "English"],
        major_strengths=["Political Science", "International Liberal Studies (SILS)", "Business"],
        aid_type="Waseda scholarships; MEXT", aid_strength=5, selectivity_score=6),
    UniversitySeed("keio", "Keio University", "Japan", "Kantō", "Tokyo",
        application_system=DIRECT, teaching_languages=["Japanese", "English"],
        major_strengths=["Economics", "Law", "Medicine", "Business (PEARL)"],
        aid_type="Keio scholarships; MEXT", aid_strength=5, selectivity_score=6),

    # South Korea
    UniversitySeed("seoul-national", "Seoul National University", "South Korea", "Seoul Capital Area", "Seoul",
        application_system=DIRECT, application_source_url="https://en.snu.ac.kr/admissions",
        short_description="Public flagship; SKY university.",
        teaching_languages=["Korean", "English"],
        major_strengths=["Engineering", "Liberal Arts", "Medicine", "Business"],
        aid_type="KGSP (Global Korea Scholarship); SNU Glo-Harmony",
        aid_strength=7, selectivity_score=8,
        full_ride_possible=True,
        aid_notes="KGSP / GKS covers full tuition + monthly stipend + airfare for international undergraduates and graduates."),
    UniversitySeed("kaist", "KAIST (Korea Advanced Institute of Science and Technology)", "South Korea", "Daejeon", "Daejeon",
        application_system=DIRECT, teaching_languages=["English", "Korean"],
        major_strengths=["Engineering", "Computer Science", "Physics", "Bioengineering"],
        aid_type="KAIST Scholarship; KGSP", aid_strength=8, selectivity_score=8,
        full_ride_possible=True,
        aid_notes="Most undergraduates receive full or partial tuition coverage; KGSP available for low-income internationals."),
    UniversitySeed("postech", "Pohang University of Science and Technology", "South Korea", "Gyeongbuk", "Pohang",
        application_system=DIRECT, teaching_languages=["English", "Korean"],
        major_strengths=["Engineering", "Computer Science", "Materials"],
        aid_type="POSTECH Scholarships (cover tuition); KGSP",
        aid_strength=8, selectivity_score=8,
        full_ride_possible=True),
    UniversitySeed("yonsei", "Yonsei University", "South Korea", "Seoul Capital Area", "Seoul",
        application_system=DIRECT, teaching_languages=["Korean", "English"],
        major_strengths=["Underwood International College (UIC)", "Business", "Medicine", "Liberal Arts"],
        aid_type="Yonsei scholarships; KGSP", aid_strength=6, selectivity_score=7),
    UniversitySeed("korea-university", "Korea University", "South Korea", "Seoul Capital Area", "Seoul",
        application_system=DIRECT, teaching_languages=["Korean", "English"],
        major_strengths=["Business", "Liberal Arts", "Engineering", "International Studies"],
        aid_type="KU Crimson; KGSP", aid_strength=6, selectivity_score=7),

    # Singapore
    UniversitySeed("nus", "National University of Singapore", "Singapore", "Singapore", "Singapore",
        application_system=DIRECT, application_source_url="https://www.nus.edu.sg/oam/apply-to-nus",
        short_description="Public flagship; one of Asia's top universities.",
        teaching_languages=["English"],
        major_strengths=["Computer Science", "Business", "Engineering", "Medicine", "Law"],
        aid_type="ASEAN Undergraduate Scholarship; Tuition Grant Scheme (work-back); NUS scholarships",
        aid_strength=7, selectivity_score=9,
        full_tuition_possible=True,
        aid_notes="Singapore MOE Tuition Grant covers most tuition for internationals who agree to work in Singapore for 3 years; ASEAN Undergraduate Scholarship covers full cost for ASEAN students."),
    UniversitySeed("ntu-singapore", "Nanyang Technological University", "Singapore", "Singapore", "Singapore",
        application_system=DIRECT, teaching_languages=["English"],
        major_strengths=["Engineering", "Business (NBS)", "Communication", "Computer Science"],
        aid_type="NTU scholarships; Tuition Grant Scheme",
        aid_strength=7, selectivity_score=8,
        full_tuition_possible=True),
    UniversitySeed("smu-singapore", "Singapore Management University", "Singapore", "Singapore", "Singapore",
        application_system=DIRECT, teaching_languages=["English"],
        major_strengths=["Business", "Economics", "Computing", "Law"],
        aid_type="SMU Scholarships; Tuition Grant Scheme",
        aid_strength=6, selectivity_score=7),

    # Hong Kong
    UniversitySeed("hku", "University of Hong Kong", "Hong Kong", "Hong Kong", "Hong Kong",
        application_system=DIRECT, teaching_languages=["English"],
        major_strengths=["Medicine", "Law", "Business", "Architecture"],
        aid_type="HKU Foundation Scholarships; HKSAR Govt Scholarship",
        aid_strength=6, selectivity_score=8,
        full_ride_possible=True),
    UniversitySeed("hkust", "Hong Kong University of Science and Technology", "Hong Kong", "Hong Kong", "Hong Kong",
        application_system=DIRECT, teaching_languages=["English"],
        major_strengths=["Business", "Engineering", "Computer Science", "Sciences"],
        aid_type="HKUST scholarships; HKSAR Govt", aid_strength=6, selectivity_score=8),
    UniversitySeed("cuhk", "Chinese University of Hong Kong", "Hong Kong", "Hong Kong", "Hong Kong",
        application_system=DIRECT, teaching_languages=["English", "Chinese (Cantonese)"],
        major_strengths=["Liberal Arts", "Engineering", "Medicine", "Business"],
        aid_type="CUHK scholarships; HKSAR Govt", aid_strength=6, selectivity_score=7),
    UniversitySeed("city-u-hk", "City University of Hong Kong", "Hong Kong", "Hong Kong", "Hong Kong",
        application_system=DIRECT, teaching_languages=["English"],
        major_strengths=["Engineering", "Business", "Creative Media", "Veterinary"],
        aid_type="CityU scholarships", aid_strength=5, selectivity_score=6),
    UniversitySeed("polyu-hk", "Hong Kong Polytechnic University", "Hong Kong", "Hong Kong", "Hong Kong",
        application_system=DIRECT, teaching_languages=["English"],
        major_strengths=["Engineering", "Hospitality (SHTM)", "Design", "Computing"],
        aid_type="PolyU scholarships", aid_strength=5, selectivity_score=6),

    # Israel
    UniversitySeed("hebrew-university", "Hebrew University of Jerusalem", "Israel", "Jerusalem District", "Jerusalem",
        application_system=DIRECT, teaching_languages=["Hebrew", "English"],
        major_strengths=["Liberal Arts", "Sciences", "Computer Science", "Law"],
        aid_type="Rothberg International School scholarships",
        aid_strength=4, selectivity_score=6),
    UniversitySeed("tel-aviv-university", "Tel Aviv University", "Israel", "Tel Aviv District", "Tel Aviv",
        application_system=DIRECT, teaching_languages=["Hebrew", "English"],
        major_strengths=["Liberal Arts", "Engineering", "Business", "Medicine"],
        aid_type="TAU International scholarships", aid_strength=4, selectivity_score=6),
    UniversitySeed("technion", "Technion - Israel Institute of Technology", "Israel", "Haifa District", "Haifa",
        application_system=DIRECT, teaching_languages=["Hebrew", "English"],
        major_strengths=["Engineering", "Computer Science", "Medicine"],
        aid_type="Technion International scholarships", aid_strength=4, selectivity_score=6),

    # Middle East
    UniversitySeed("nyu-abu-dhabi", "NYU Abu Dhabi", "United Arab Emirates", "Abu Dhabi", "Abu Dhabi",
        application_system=COMMON_APP, is_common_app=True, teaching_languages=["English"],
        application_source_url="https://nyuad.nyu.edu/en/admissions.html",
        short_description="Liberal-arts-focused NYU portal campus; one of the most selective in the Middle East.",
        major_strengths=["Liberal Arts", "Engineering", "Computer Science", "Economics"],
        aid_type="Need-blind; meets 100% need + travel + insurance",
        aid_strength=10, selectivity_score=10,
        full_ride_possible=True, full_tuition_possible=True,
        aid_notes="Need-blind for all applicants; admitted students receive aid covering 100% of demonstrated need including travel and insurance.",
        funding_source_url="https://nyuad.nyu.edu/en/admissions/financial-aid.html",
        funding_source_title="NYU Abu Dhabi Financial Aid"),
    UniversitySeed("aus-sharjah", "American University of Sharjah", "United Arab Emirates", "Sharjah", "Sharjah",
        application_system=DIRECT, teaching_languages=["English"],
        major_strengths=["Engineering", "Architecture", "Business"],
        aid_type="Merit (Chancellor's, Deans's)", aid_strength=5, selectivity_score=5),
    UniversitySeed("kaust", "King Abdullah University of Science and Technology", "Saudi Arabia", "Makkah", "Thuwal",
        application_system=DIRECT, teaching_languages=["English"],
        major_strengths=["Engineering", "Computer Science", "Materials", "Marine Science"],
        aid_type="KAUST Fellowship (full ride)", aid_strength=10, selectivity_score=8,
        full_ride_possible=True,
        aid_notes="KAUST is graduate-only; all admitted students receive a fellowship covering tuition, stipend, housing, and medical insurance."),

    # Turkey
    UniversitySeed("bogazici", "Boğaziçi University", "Turkey", "Marmara", "Istanbul",
        application_system=DIRECT, teaching_languages=["English", "Turkish"],
        major_strengths=["Engineering", "Economics", "Liberal Arts"],
        aid_type="Türkiye Burslari (Turkey Scholarships)", aid_strength=5, selectivity_score=6,
        full_ride_possible=True),
    UniversitySeed("koc-university", "Koç University", "Turkey", "Marmara", "Istanbul",
        application_system=DIRECT, teaching_languages=["English"],
        major_strengths=["Business", "Engineering", "Liberal Arts"],
        aid_type="Anatolian Scholarship; Türkiye Burslari", aid_strength=5, selectivity_score=6,
        full_ride_possible=True),
    UniversitySeed("metu", "Middle East Technical University", "Turkey", "Central Anatolia", "Ankara",
        application_system=DIRECT, teaching_languages=["English", "Turkish"],
        major_strengths=["Engineering", "Architecture", "Sciences"],
        aid_type="Türkiye Burslari", aid_strength=5, selectivity_score=6,
        full_ride_possible=True),
    UniversitySeed("bilkent", "Bilkent University", "Turkey", "Central Anatolia", "Ankara",
        application_system=DIRECT, teaching_languages=["English"],
        major_strengths=["Engineering", "Business", "Liberal Arts"],
        aid_type="Bilkent merit scholarships", aid_strength=5, selectivity_score=5),
]


# ---------------------------------------------------------------------------
# Australia + New Zealand (8)
# ---------------------------------------------------------------------------
OCEANIA: list[UniversitySeed] = [
    UniversitySeed("u-melbourne", "University of Melbourne", "Australia", "Victoria", "Melbourne",
        application_system=DIRECT, teaching_languages=["English"],
        major_strengths=["Liberal Arts", "Medicine", "Engineering", "Business"],
        aid_type="Melbourne International Undergraduate Scholarship",
        aid_strength=4, selectivity_score=7),
    UniversitySeed("u-sydney", "University of Sydney", "Australia", "New South Wales", "Sydney",
        application_system=DIRECT, teaching_languages=["English"],
        major_strengths=["Medicine", "Architecture", "Veterinary Science", "Business"],
        aid_type="Vice-Chancellor's International Scholarships",
        aid_strength=4, selectivity_score=6),
    UniversitySeed("anu", "Australian National University", "Australia", "ACT", "Canberra",
        application_system=DIRECT, teaching_languages=["English"],
        major_strengths=["International Relations", "Sciences", "Liberal Arts", "Public Policy"],
        aid_type="ANU Chancellor's; Tuckwell (Australians only)",
        aid_strength=4, selectivity_score=6),
    UniversitySeed("unsw", "University of New South Wales", "Australia", "New South Wales", "Sydney",
        application_system=DIRECT, teaching_languages=["English"],
        major_strengths=["Engineering", "Business", "Computer Science", "Medicine"],
        aid_type="UNSW International Scholarships", aid_strength=4, selectivity_score=6),
    UniversitySeed("u-queensland", "University of Queensland", "Australia", "Queensland", "Brisbane",
        application_system=DIRECT, teaching_languages=["English"],
        major_strengths=["Engineering", "Veterinary Science", "Business"],
        aid_type="UQ International Scholarships", aid_strength=4, selectivity_score=5),
    UniversitySeed("monash", "Monash University", "Australia", "Victoria", "Melbourne",
        application_system=DIRECT, teaching_languages=["English"],
        major_strengths=["Pharmacy", "Business", "Engineering", "Medicine"],
        aid_type="Monash International Merit Scholarships",
        aid_strength=4, selectivity_score=5),
    UniversitySeed("uwa", "University of Western Australia", "Australia", "Western Australia", "Perth",
        application_system=DIRECT, teaching_languages=["English"],
        major_strengths=["Mining Engineering", "Marine Science", "Liberal Arts"],
        aid_type="UWA Global Excellence", aid_strength=4, selectivity_score=5),
    UniversitySeed("auckland", "University of Auckland", "New Zealand", "Auckland", "Auckland",
        application_system=DIRECT, teaching_languages=["English"],
        major_strengths=["Liberal Arts", "Medicine", "Engineering"],
        aid_type="UoA International Excellence", aid_strength=4, selectivity_score=5),
]


# ---------------------------------------------------------------------------
# Canada (10)
# ---------------------------------------------------------------------------
CANADA: list[UniversitySeed] = [
    UniversitySeed("u-toronto", "University of Toronto", "Canada", "Ontario", "Toronto",
        application_system="OUAC 105",
        application_source_url="https://www.applyontario.ca",
        short_description="Public research university; flagship of Canada.",
        teaching_languages=["English"],
        major_strengths=["Computer Science", "Engineering", "Medicine", "Business (Rotman)"],
        aid_type="Lester B. Pearson Scholarship (full ride); UofT Scholars",
        aid_strength=7, selectivity_score=7,
        full_ride_possible=True,
        aid_notes="Lester B. Pearson International Scholarship covers tuition + books + residence + incidental fees for ~37 students/year."),
    UniversitySeed("mcgill", "McGill University", "Canada", "Quebec", "Montreal",
        application_system=DIRECT, teaching_languages=["English"],
        major_strengths=["Medicine", "Liberal Arts", "Engineering", "Law"],
        aid_type="McGill Entrance Scholarships; need-based aid",
        aid_strength=5, selectivity_score=7),
    UniversitySeed("ubc", "University of British Columbia", "Canada", "British Columbia", "Vancouver",
        application_system=DIRECT, teaching_languages=["English"],
        major_strengths=["Engineering", "Forestry", "Business (Sauder)", "Computer Science"],
        aid_type="International Major Entrance; International Scholars",
        aid_strength=6, selectivity_score=6,
        full_ride_possible=True,
        aid_notes="UBC International Scholars Program (Karen McKellin / Donald A. Wehrung) covers full cost for high-need students from low-income countries."),
    UniversitySeed("waterloo", "University of Waterloo", "Canada", "Ontario", "Waterloo",
        application_system="OUAC 105", teaching_languages=["English"],
        major_strengths=["Computer Science", "Engineering", "Mathematics", "Co-op"],
        aid_type="Merit (President's; International)", aid_strength=4, selectivity_score=6),
    UniversitySeed("u-alberta", "University of Alberta", "Canada", "Alberta", "Edmonton",
        application_system=DIRECT, teaching_languages=["English"],
        major_strengths=["Engineering", "Business", "Sciences"],
        aid_type="Merit (International Admissions)", aid_strength=4, selectivity_score=5),
    UniversitySeed("mcmaster", "McMaster University", "Canada", "Ontario", "Hamilton",
        application_system="OUAC 105", teaching_languages=["English"],
        major_strengths=["Engineering", "Health Sciences", "Business (DeGroote)"],
        aid_type="Merit; need-based International Excellence",
        aid_strength=4, selectivity_score=6),
    UniversitySeed("western-university", "Western University", "Canada", "Ontario", "London",
        application_system="OUAC 105", teaching_languages=["English"],
        major_strengths=["Business (Ivey)", "Medicine", "Engineering"],
        aid_type="Merit (International President's)", aid_strength=4, selectivity_score=5),
    UniversitySeed("queens-university", "Queen's University", "Canada", "Ontario", "Kingston",
        application_system="OUAC 105", teaching_languages=["English"],
        major_strengths=["Commerce", "Engineering", "Liberal Arts"],
        aid_type="International Admission Awards", aid_strength=4, selectivity_score=6),
    UniversitySeed("u-calgary", "University of Calgary", "Canada", "Alberta", "Calgary",
        application_system=DIRECT, teaching_languages=["English"],
        major_strengths=["Engineering", "Business (Haskayne)", "Veterinary Medicine"],
        aid_type="International Entrance Scholarships", aid_strength=4, selectivity_score=5),
    UniversitySeed("concordia", "Concordia University", "Canada", "Quebec", "Montreal",
        application_system=DIRECT, teaching_languages=["English"],
        major_strengths=["Communication", "Business (JMSB)", "Fine Arts"],
        aid_type="Concordia Presidential Scholarships", aid_strength=4, selectivity_score=4),
]


# ---------------------------------------------------------------------------
# Kazakhstan + regional (12)
# ---------------------------------------------------------------------------
REGIONAL: list[UniversitySeed] = [
    UniversitySeed("nazarbayev-university", "Nazarbayev University", "Kazakhstan", "Akmola Region", "Astana",
        application_system=DIRECT,
        application_source_url="https://nu.edu.kz/admissions",
        short_description="English-medium research university in Astana modeled on Western universities.",
        teaching_languages=["English"],
        major_strengths=["Engineering", "Sciences", "Liberal Arts", "Business", "Medicine"],
        aid_type="State scholarship (full ride for selected students)",
        aid_strength=10, selectivity_score=8,
        full_ride_possible=True, full_tuition_possible=True,
        aid_notes="Vast majority of Kazakhstani undergraduates study tuition-free under the state scholarship.",
        funding_source_url="https://nu.edu.kz/admissions/financing-options",
        funding_source_title="Nazarbayev University Financing Options"),
    UniversitySeed("kimep", "KIMEP University", "Kazakhstan", "Almaty Region", "Almaty",
        application_system=DIRECT, teaching_languages=["English"],
        major_strengths=["Business", "Economics", "Public Administration", "Law"],
        aid_type="Merit (Presidential, Trustee)", aid_strength=5, selectivity_score=5),
    UniversitySeed("aitu-astana", "Astana IT University", "Kazakhstan", "Akmola Region", "Astana",
        application_system=DIRECT, teaching_languages=["English", "Russian", "Kazakh"],
        major_strengths=["Computer Science", "Cybersecurity", "Data Science"],
        aid_type="State grants; merit", aid_strength=6, selectivity_score=4),
    UniversitySeed("almaty-management-university", "Almaty Management University (AlmaU)", "Kazakhstan", "Almaty Region", "Almaty",
        application_system=DIRECT, teaching_languages=["English", "Russian"],
        major_strengths=["Management", "Business", "Tourism"],
        aid_type="Merit", aid_strength=4, selectivity_score=4),
    UniversitySeed("hse-moscow", "HSE University (Higher School of Economics)", "Russia", "Central Federal District", "Moscow",
        application_system=DIRECT, teaching_languages=["English", "Russian"],
        major_strengths=["Economics", "Mathematics", "Computer Science", "Public Policy"],
        aid_type="HSE Global Scholarship Competition; merit",
        aid_strength=5, selectivity_score=6),
    UniversitySeed("mipt", "Moscow Institute of Physics and Technology", "Russia", "Moscow Region", "Dolgoprudny",
        application_system=DIRECT, teaching_languages=["Russian", "English"],
        major_strengths=["Physics", "Mathematics", "Computer Science"],
        aid_type="State quota; merit", aid_strength=5, selectivity_score=7,
        full_ride_possible=True),
    UniversitySeed("mgu", "Lomonosov Moscow State University", "Russia", "Central Federal District", "Moscow",
        application_system=DIRECT, teaching_languages=["Russian", "English"],
        major_strengths=["Sciences", "Liberal Arts", "Mathematics"],
        aid_type="State quota for international students",
        aid_strength=5, selectivity_score=6,
        full_ride_possible=True),
    UniversitySeed("au-of-central-asia", "University of Central Asia", "Kyrgyzstan", "Naryn", "Naryn",
        application_system=DIRECT, teaching_languages=["English"],
        major_strengths=["Earth and Environmental Sciences", "Communications", "Computer Science"],
        aid_type="Need-based + merit (subsidized for Central Asian students)",
        aid_strength=8, selectivity_score=5,
        full_ride_possible=True,
        aid_notes="Founded by Aga Khan Development Network; tuition heavily subsidized for residents of Kazakhstan, Kyrgyzstan, and Tajikistan."),
    UniversitySeed("kdi-school", "KDI School of Public Policy and Management", "South Korea", "Sejong", "Sejong",
        application_system=DIRECT, teaching_languages=["English"],
        major_strengths=["Public Policy", "Development Economics", "Public Management"],
        aid_type="KDIS Fellowship (full)", aid_strength=9, selectivity_score=6,
        full_ride_possible=True,
        aid_notes="Graduate-only; ~80% of international students receive a full scholarship covering tuition, stipend, and airfare."),
    UniversitySeed("university-of-tartu", "University of Tartu", "Estonia", "Tartu County", "Tartu",
        application_system=DIRECT, teaching_languages=["English", "Estonian"],
        major_strengths=["Computer Science", "Liberal Arts", "Sciences"],
        aid_type="Estonian Government scholarship; UT scholarships",
        aid_strength=4, selectivity_score=4),
    UniversitySeed("charles-university", "Charles University", "Czech Republic", "Prague", "Prague",
        application_system=DIRECT, teaching_languages=["Czech", "English"],
        major_strengths=["Medicine", "Liberal Arts", "Sciences"],
        aid_type="Czech Government Scholarship; merit",
        aid_strength=4, selectivity_score=4),
    UniversitySeed("ku-leuven", "KU Leuven", "Belgium", "Flemish Brabant", "Leuven",
        application_system=DIRECT, teaching_languages=["English", "Dutch"],
        major_strengths=["Engineering", "Medicine", "Sciences", "Liberal Arts"],
        aid_type="VLIR-UOS scholarships; Science@Leuven",
        aid_strength=4, selectivity_score=5),
]


# ---------------------------------------------------------------------------
# Final flat catalog
# ---------------------------------------------------------------------------
ALL_UNIVERSITIES: list[UniversitySeed] = US + UK + EUROPE + ASIA + OCEANIA + CANADA + REGIONAL


def _to_dict(seed: UniversitySeed) -> dict:
    return {
        "slug": seed.slug,
        "name": seed.name,
        "country": seed.country,
        "region": seed.region,
        "city": seed.city,
        "application_system": seed.application_system,
        "application_source_url": seed.application_source_url,
        "short_description": seed.short_description,
        "weight_preset": seed.weight_preset,
        "is_common_app": seed.is_common_app,
        "teaching_languages": seed.teaching_languages,
        "major_strengths": seed.major_strengths,
        "education_years_required": seed.education_years_required,
        "school_years_note": seed.school_years_note,
        "aid_type": seed.aid_type,
        "aid_strength": seed.aid_strength,
        "selectivity_score": seed.selectivity_score,
        "full_ride_possible": seed.full_ride_possible,
        "full_tuition_possible": seed.full_tuition_possible,
        "aid_notes": seed.aid_notes,
        "funding_source_url": seed.funding_source_url,
        "funding_source_title": seed.funding_source_title,
        "eligibility_notes": seed.eligibility_notes,
        "is_active": True,
    }


def seed_universities(db: Session | None = None) -> int:
    """Upsert the starter universities into the database.

    Returns the number of records created or updated.
    """
    own_session = db is None
    session = db or SessionLocal()
    try:
        touched = 0
        for seed in ALL_UNIVERSITIES:
            payload = _to_dict(seed)
            existing = (
                session.query(University).filter(University.slug == seed.slug).first()
            )
            if existing:
                for field_name, value in payload.items():
                    setattr(existing, field_name, value)
            else:
                session.add(University(**payload))
            touched += 1
        session.commit()
        return touched
    finally:
        if own_session:
            session.close()


if __name__ == "__main__":
    count = seed_universities()
    print(f"Upserted {count} universities into the database.")
